

trigger:
  - main

pool:
  vmImage: "ubuntu-latest"

variables:
  solution: "**/*.sln"
  buildPlatform: "Any CPU"
  buildConfiguration: "Release"

steps:
  - task: NuGetToolInstaller@1

  - task: NuGetCommand@2
    inputs:
      restoreSolution: "$(solution)"


  - task: CmdLine@1
    displayName: FOSSA
    inputs:
      script: |
        curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | bash
        FOSSA_API_KEY=8229158d3befa3c8ee0db34e3714e394
        fossa
      